### PR TITLE
Use `txid_limit` only in `get_oldest_tx()`

### PR DESCRIPTION
**Pull request by ouziel-slama**

### CODE REVIEW

**Comment by ouziel-slama** [comment]
(not tested)

**Comment by ouziel-slama** [comment]
works! thanks @mattmarcello !

**Comment by adamkrellenstein** [comment]
hm, I don't understand this...

**Comment by ouziel-slama** [comment]
The txid_limit variable is used in several functions including `get_utxos()` and `get_oldest_tx()`. There is only `get_oldest_tx()` for which we are obliged to leave the `txid_limit` equal to 100 so as not to break the consensus. For the other functions, which are used to compose transactions, we do not need to keep this parameter which prevents, for example, composing a transaction with an address that has more than 100 transactions.

**Review by adamkrellenstein — APPROVED** [review]

**Pull request merged**
